### ISSUE TITLE
Why doesn't anyone answer?

### ISSUE THREAD

**Issue by gfsoluzioni** [open-admin-org/open-admin#151]
I've created tickets, but no one ever bothers to reply to me. Why? Do I make you dislike me?

**Comment by RCyrix** [comment]
Hi there, i will answer when I am able, if no one is able to answer because we are all living our own lives, then please be patient, Are you going to pay for time and effort? are you going to let me invoice you for the time i spend on your problems?

 This is a community framework, Not something built for you to suite you, The community will respond if and when it can. If this is not suitable for you please dive into the code and make your own plan until the community is able to respond and have a look at what the problem is. This is not a commercial project. You are not paying anyone and honestly cannot rush rush anyone.

**Comment by gfsoluzioni** [comment]
> Salve, risponderò quando potrò, se nessuno è in grado di rispondere perché viviamo tutti la nostra vita, allora per favore sii paziente, pagherai tempo e fatica? mi permetterai di fatturarti il ​​tempo che dedico ai tuoi problemi?
> 
> Questa è una struttura comunitaria, non qualcosa costruito su misura per te, la comunità risponderà se e quando potrà. Se questo non è adatto a te, immergiti nel codice e crea il tuo piano finché la comunità non sarà in grado di rispondere e dai un'occhiata a quale è il problema. Questo non è un progetto commerciale. Non stai pagando nessuno e onestamente non puoi affrettare nessuno.

I reported a bug (#148) that I have no expertise on. I see that someone who writes after me responds immediately, while my tickets are left unanswered for weeks. I thank you in advance.

PS:
I'm glad you took the time to respond to me in this vent ticket
