### ISSUE TITLE
user settings avatar

### ISSUE THREAD

**Issue by Abdullajon8111** [open-admin-org/open-admin#62]
![image](https://github.com/open-admin-org/open-admin/assets/32351272/7df7ed82-83b8-4ef7-8c13-f6f0ecd3d41c)
user settings avatar not viewed

**Comment by open-admin-org** [comment]
@Abdullajon8111 What is the url its trying to load? And what is you host url? Maybe take a screenshot of the network tab in the developer tools

**Comment by RCyrix** [comment]
Hi there, I've found the same issue

It seems to be repeating the URL 

![image](https://github.com/open-admin-org/open-admin/assets/124294361/a7d8a4d1-0b5e-4543-bb9b-63c858ec8964)


![image](https://github.com/open-admin-org/open-admin/assets/124294361/4571cff9-f473-4de9-9b69-2b9bf5d34ed2)

**Comment by RCyrix** [comment]
Hi there, 

i played around a bit and it the issue seems to be in the model, 

`    public function getAvatarAttribute($avatar)
    {
        if (url()->isValidUrl($avatar)) {
            return $avatar;
        }

        $disk = config('admin.upload.disk');

        if ($avatar && array_key_exists($disk, config('filesystems.disks'))) {
            return Storage::disk(config('admin.upload.disk'))->url($avatar);
        }

        $default = config('admin.default_avatar') ?: '/vendor/open-admin/open-admin/gfx/user.svg';

        return admin_asset($default);
    }`

When getting file info from 

/public/vendor/open-admin/fields/file-upload/file-upload.js

![image](https://github.com/open-admin-org/open-admin/assets/124294361/88c7661f-e353-43a0-b81c-3936b8748ed7)

![image](https://github.com/open-admin-org/open-admin/assets/124294361/b0c9e938-6173-42a4-ac5c-a4854c3c0417)


With the model override, it adds the storage url already, so it ends up adding it twice for user

**Comment by RCyrix** [comment]
![image](https://github.com/open-admin-org/open-admin/assets/124294361/56539edd-21c3-42d2-9114-cb5c93558811)

This being the offender, if the storage wrapper is removed, it works passing only the file name to the file upload script 

![image](https://github.com/open-admin-org/open-admin/assets/124294361/fab2fe51-8a00-4ecc-86b0-4e6aa57f08e8)

**Comment by RCyrix** [comment]
![image](https://github.com/open-admin-org/open-admin/assets/124294361/1fc86b26-7e8e-4402-af7c-8ff60cd852c0)

**Comment by Rolliboy** [comment]
![immagine](https://github.com/open-admin-org/open-admin/assets/14222930/61a22468-ffaa-458f-9a4f-b0de81e93224)

Same problem, here a screenshot of the image opened showing the error on path 
I also expect the uploaded image not a general svg

**Comment by andrew-m-p** [comment]
Changing code like this seems to fix it (in getAvatarAttribute) :

if ($avatar && array_key_exists($disk, config('filesystems.disks'))) {
            return Storage::disk()->url($avatar);
        }

**Comment by open-admin-org** [comment]
Thanks all for the feedback. 

Problem lies in the way the file / image field works. This uses the storage folder which is different from public/vendor files for the default user image. These working could not be properly united.  

Now the avatar on the default user model now just returns the database value. This way the file thumbnail will not show at all when its not set. The header now uses a different fake-attribute (headerAvatar) that hooks into the avatar attribute returing the default avatar or user.svg when its empty.

Fixed in develop will merge soon.

**Comment by goldensio** [comment]
i have the same issue now in july 2024, but the info here are outdated, how can i fix?
